when:
  branch: ${CI_REPO_DEFAULT_BRANCH}
  event: tag

variables:
  - &base Dockerfile.base
  - &agcr ${CI_FORGE_URL:8}/orvilleq/godot-base
  - &ghcr ghcr.io/orvilleq/godot-base

steps:
  - name: base-release
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: *base
      platforms: linux/amd64,linux/386,linux/arm64/v8,linux/arm/v7
      repo:
        - *agcr
        - *ghcr
      tags: ${CI_COMMIT_TAG}
      logins:
        - registry: ${CI_FORGE_URL}
          username: orvilleq
          password:
            from_secret: ag_token
        - registry: https://ghcr.io
          username: orvilleq
          password:
            from_secret: gh_token
    when:
      event: tag
