when:
  branch:
    exclude: ${CI_REPO_DEFAULT_BRANCH}
  event: [push, pull_request]
  path:
    include: ['.woodpecker/*', 'Dockerfile*', '*.sh']


variables:
  - &standard Dockerfile
  - &dotnet Dockerfile.dotnet
  - &standard_platforms linux/amd64,linux/386,linux/arm64/v8,linux/arm/v7
  - &dotnet_platforms linux/amd64,linux/arm64/v8,linux/arm/v7
  - &cr ${CI_FORGE_URL:8}/${CI_REPO_OWNER,,}/godot-ci

steps:
  - name: artifact
    image: debian:12-slim
    commands:
      - sh artifact.sh

  - name: test:standard
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: *standard
      platforms: *standard_platforms
      provenance: false
      repo: *cr
      tags: test
      registry: ${CI_FORGE_URL}
      dry-run: true
    depends_on: artifact
    when:
      path:
        include:
          - *standard
          - '.woodpecker/*'
          - '*.sh'

  - name: test:dotnet
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: *dotnet
      platforms: *dotnet_platforms
      provenance: false
      repo: *cr
      tags: test-dotnet
      registry: ${CI_FORGE_URL}
      dry-run: true
    depends_on: artifact
    when:
      path:
        include:
          - *dotnet
          - '.woodpecker/*'
          - '*.sh'
