when:
  branch:
    exclude: ${CI_REPO_DEFAULT_BRANCH}
  event: [push, pull_request]

variables:
  - &base Dockerfile.base
  - &platforms linux/amd64,linux/386,linux/arm64/v8,linux/arm/v7
  - &agcr ${CI_FORGE_URL:8}/orvilleq/godot-base

steps:
  - name: base-test
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: *base
      platforms: *platforms
      provenance: false
      repo: *agcr
      tags: test
      registry: ${CI_FORGE_URL}
      dry-run: true
    when:
      path: *base
