when:
  branch:
    exclude: ${CI_REPO_DEFAULT_BRANCH}
  event: [push, pull_request]

variables:
  - &file Dockerfile
  - &platforms linux/amd64,linux/386,linux/arm64/v8,linux/arm/v7
  - &cr ${CI_FORGE_URL:8}/${CI_REPO_OWNER,,}/godot-ci

steps:
  - name: artifact
    image: debian:12-slim
    commands:
      - sh artifact.sh

  - name: build-test
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: *file
      platforms: *platforms
      provenance: false
      repo: *cr
      tags: test
      registry: ${CI_FORGE_URL}
      dry-run: true
    depends_on: artifact
    when:
      path: *file
